name: Wanga Theme
markdown: redcarpet
highlighter: pygments
baseurl: /sandpit
permalink: /:year/:month/:title/
relative_permalinks: false
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: davidlennox-sandpit    
ga_id: #
ga_username: #        
timezone: #     