name: Wanga Theme
markdown: redcarpet
pygments: true
baseurl: /sandpit
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: davidlennox-sandpit
    
ga_id: #
ga_username: #
        
timezone: #
       
