name: Wanga Theme
markdown: kramdown
highlighter: pygments
baseurl: /sandpit
permalink: /blog/:year/:title
imgs: /assets/imgs
relative_permalinks: false
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: davidlennox-sandpit    
ga_id: #
ga_username: #        
timezone: #     
page_categories:
- recipes
- patterns
